#!/usr/bin/env python3.8

import subprocess

filename  = input("What should we name the file? ")
content = input("What should go in the file? ")

filecreate = subprocess.run(['touch', filename])

fileopen = open(filename, 'w')

lines = []
while True:
    line = input()
    if content:
        lines.append(content)
    else:
        break
text  = '\n'.join(lines)

