#!/usr/bin/env python3.8

import subprocess

filename  = input("What should we name the file? ")
content = print(f"What should go in the file?")

filecreate = subprocess.run(['touch', filename])

#fileopen = open(filename, 'w')

#filewrite = fileopen.writelines(content)

with open(filename, 'w') as f:
    lines = []

    while True:
        line = input()
        if line:
            lines.append(line)
        else:
            break
    text = '\n'.join(lines)
    f.writelines(text)



